before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq odbc-postgresql unixodbc-dev

language: c

compiler: gcc

addons:
  postgresql: "9.3"

env:
  global:
    - secure: TnTGMjGO4i2SgcDtqOKADL1/0iHI3SomEDqn2/9+5vepTmOxPTkEYSwgtcvw0HLBnB5rHFvpi5FcUZCXEbe9OuaR2re2nyQFOw5Cz03CB9L4iNwtlE1OUUhCPsKI7skrkhTjDxJ/eXdaKOY2ER6Wt55BzKaQysRSkf6ApJKbFjE=
    - PGVERSION="9.3"

before_script:
  - source $TRAVIS_BUILD_DIR/travis_linux_env.sh

script:
  - cd $IRODS_HOME
  - export CFLAGS=-fPIC ; make
  - cd $TRAVIS_BUILD_DIR

after_script:
  - sudo -E -u postgres $TRAVIS_BUILD_DIR/setup_pgusers.sh
  - sudo -E -u postgres $TRAVIS_BUILD_DIR/irodscontrol psetup
  - sudo mkdir -p /usr/local/var/lib/irods/Vault
  - sudo chown $USER:$USER /usr/local/var/lib/irods/Vault
  - $TRAVIS_BUILD_DIR/smoke_test.sh

after_failure:
  - cat $IRODS_HOME/server/log/rodsLog.*

after_success:
  - cd $TRAVIS_BUILD_DIR
  - tar -c -f /tmp/irods.tar.gz -z --exclude ./.git --exclude ./CVSROOT --exclude README.md --exclude .travis.yml --exclude='*.o' --exclude='*.c' .
  - echo "branch '$TRAVIS_BRANCH', tag '$TRAVIS_TAG', commit '$TRAVIS_COMMIT', build '$TRAVIS_BUILD_NUMBER'"

deploy:
  provider: releases
  api-key: $GH_OAUTH
  file: /tmp/irods.tar.gz
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
