before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq odbc-postgresql unixodbc-dev

language: c

compiler: gcc

addons:
  postgresql: "9.3"

env:
  global:
    - secure: TnTGMjGO4i2SgcDtqOKADL1/0iHI3SomEDqn2/9+5vepTmOxPTkEYSwgtcvw0HLBnB5rHFvpi5FcUZCXEbe9OuaR2re2nyQFOw5Cz03CB9L4iNwtlE1OUUhCPsKI7skrkhTjDxJ/eXdaKOY2ER6Wt55BzKaQysRSkf6ApJKbFjE=

    - PGHOME=/usr/lib/postgresql/9.3
    - PGDATA=/var/ramfs/postgresql/9.3/main
    - PGCONF=/etc/postgresql/9.3/main/postgresql.conf
    - PGCTL=$PGHOME/bin/pg_ctl
    - PGPASSWORD=postgres
    - ODBCINI=$TRAVIS_BUILD_DIR/odbc.ini
    - IRODS_HOME=$TRAVIS_BUILD_DIR/iRODS
    - IRODS_AUTH=$TRAVIS_BUILD_DIR/irods_auth.dat
    - ICAT_CLEAN=$TRAVIS_BUILD_DIR/icat_dump.sql
    - irodsEnvFile=$TRAVIS_BUILD_DIR/irods_env.conf

before_script:
  - sudo -u postgres createuser -D -r -s icat
  - sudo -u postgres sh -c "echo ALTER USER icat WITH PASSWORD \'icat\' | psql"
  - sudo -u postgres sh -c "echo ALTER USER postgres WITH PASSWORD \'$PGPASSWORD\' | psql"

script:
  - cd $IRODS_HOME
  - export CFLAGS=-fPIC ; make
  - cd $TRAVIS_BUILD_DIR

after_script:
  - sudo -E -u postgres $TRAVIS_BUILD_DIR/irodscontrol psetup
  - $TRAVIS_BUILD_DIR/irodscontrol istart
  - sudo -E -u postgres $TRAVIS_BUILD_DIR/irodscontrol status
  - sleep 10
  - echo irods | script -q -c "$IRODS_HOME/clients/icommands/bin/iinit" > /dev/null
  - $IRODS_HOME/clients/icommands/bin/ienv
  - $IRODS_HOME/clients/icommands/bin/ils
  - $TRAVIS_BUILD_DIR/irodscontrol istop
  - cat $IRODS_HOME/server/log/rodsLog.*

# after_success: cd $TRAVIS_BUILD_DIR ; tar -c -f irods.tar.gz -z --exclude='*.o' --exclude='*.c' iRODS/

deploy:
  provider: releases
  api-key: $GH_OAUTH
  file: irods.tar.gz
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_BRANCH = travis-build"
    branch: travis-build

branches:
  only:
  - travis-build
